// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createInquiryStmt, err = db.PrepareContext(ctx, createInquiry); err != nil {
		return nil, fmt.Errorf("error preparing query CreateInquiry: %w", err)
	}
	if q.createProductStmt, err = db.PrepareContext(ctx, createProduct); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProduct: %w", err)
	}
	if q.getAdminByEmailStmt, err = db.PrepareContext(ctx, getAdminByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetAdminByEmail: %w", err)
	}
	if q.getAllProjectsStmt, err = db.PrepareContext(ctx, getAllProjects); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllProjects: %w", err)
	}
	if q.getHighlightedProjectsStmt, err = db.PrepareContext(ctx, getHighlightedProjects); err != nil {
		return nil, fmt.Errorf("error preparing query GetHighlightedProjects: %w", err)
	}
	if q.getLatestNewsStmt, err = db.PrepareContext(ctx, getLatestNews); err != nil {
		return nil, fmt.Errorf("error preparing query GetLatestNews: %w", err)
	}
	if q.getProductBySlugStmt, err = db.PrepareContext(ctx, getProductBySlug); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductBySlug: %w", err)
	}
	if q.getProductsStmt, err = db.PrepareContext(ctx, getProducts); err != nil {
		return nil, fmt.Errorf("error preparing query GetProducts: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createInquiryStmt != nil {
		if cerr := q.createInquiryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createInquiryStmt: %w", cerr)
		}
	}
	if q.createProductStmt != nil {
		if cerr := q.createProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProductStmt: %w", cerr)
		}
	}
	if q.getAdminByEmailStmt != nil {
		if cerr := q.getAdminByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAdminByEmailStmt: %w", cerr)
		}
	}
	if q.getAllProjectsStmt != nil {
		if cerr := q.getAllProjectsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllProjectsStmt: %w", cerr)
		}
	}
	if q.getHighlightedProjectsStmt != nil {
		if cerr := q.getHighlightedProjectsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getHighlightedProjectsStmt: %w", cerr)
		}
	}
	if q.getLatestNewsStmt != nil {
		if cerr := q.getLatestNewsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLatestNewsStmt: %w", cerr)
		}
	}
	if q.getProductBySlugStmt != nil {
		if cerr := q.getProductBySlugStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductBySlugStmt: %w", cerr)
		}
	}
	if q.getProductsStmt != nil {
		if cerr := q.getProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductsStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                         DBTX
	tx                         *sql.Tx
	createInquiryStmt          *sql.Stmt
	createProductStmt          *sql.Stmt
	getAdminByEmailStmt        *sql.Stmt
	getAllProjectsStmt         *sql.Stmt
	getHighlightedProjectsStmt *sql.Stmt
	getLatestNewsStmt          *sql.Stmt
	getProductBySlugStmt       *sql.Stmt
	getProductsStmt            *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                         tx,
		tx:                         tx,
		createInquiryStmt:          q.createInquiryStmt,
		createProductStmt:          q.createProductStmt,
		getAdminByEmailStmt:        q.getAdminByEmailStmt,
		getAllProjectsStmt:         q.getAllProjectsStmt,
		getHighlightedProjectsStmt: q.getHighlightedProjectsStmt,
		getLatestNewsStmt:          q.getLatestNewsStmt,
		getProductBySlugStmt:       q.getProductBySlugStmt,
		getProductsStmt:            q.getProductsStmt,
	}
}
