// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Admin struct {
	ID           int32        `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	LastLogin    sql.NullTime `json:"last_login"`
}

type Inquiry struct {
	ID           int32                 `json:"id"`
	FullName     string                `json:"full_name"`
	Email        string                `json:"email"`
	Phone        sql.NullString        `json:"phone"`
	ServiceType  sql.NullString        `json:"service_type"`
	Message      string                `json:"message"`
	EstimateData pqtype.NullRawMessage `json:"estimate_data"`
	Status       sql.NullString        `json:"status"`
	CreatedAt    sql.NullTime          `json:"created_at"`
}

type News struct {
	ID          int32          `json:"id"`
	Title       string         `json:"title"`
	Content     string         `json:"content"`
	ImageUrl    sql.NullString `json:"image_url"`
	PublishedAt sql.NullTime   `json:"published_at"`
}

type Product struct {
	ID          int32                 `json:"id"`
	Name        string                `json:"name"`
	Slug        string                `json:"slug"`
	Description sql.NullString        `json:"description"`
	Price       string                `json:"price"`
	Category    string                `json:"category"`
	ImageUrl    sql.NullString        `json:"image_url"`
	StockLevel  sql.NullInt32         `json:"stock_level"`
	IsFeatured  sql.NullBool          `json:"is_featured"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
}

type Project struct {
	ID             int32          `json:"id"`
	Title          string         `json:"title"`
	Client         sql.NullString `json:"client"`
	Location       sql.NullString `json:"location"`
	Category       string         `json:"category"`
	Summary        string         `json:"summary"`
	ThumbnailUrl   string         `json:"thumbnail_url"`
	GalleryUrls    []string       `json:"gallery_urls"`
	CompletionYear sql.NullInt32  `json:"completion_year"`
	IsHighlight    sql.NullBool   `json:"is_highlight"`
	CreatedAt      sql.NullTime   `json:"created_at"`
}
