// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const createInquiry = `-- name: CreateInquiry :one
INSERT INTO inquiries (full_name, email, phone, service_type, message, estimate_data)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, full_name, email, phone, service_type, message, estimate_data, status, created_at
`

type CreateInquiryParams struct {
	FullName     string                `json:"full_name"`
	Email        string                `json:"email"`
	Phone        sql.NullString        `json:"phone"`
	ServiceType  sql.NullString        `json:"service_type"`
	Message      string                `json:"message"`
	EstimateData pqtype.NullRawMessage `json:"estimate_data"`
}

func (q *Queries) CreateInquiry(ctx context.Context, arg CreateInquiryParams) (Inquiry, error) {
	row := q.queryRow(ctx, q.createInquiryStmt, createInquiry,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.ServiceType,
		arg.Message,
		arg.EstimateData,
	)
	var i Inquiry
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.ServiceType,
		&i.Message,
		&i.EstimateData,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, slug, description, price, category, image_url, stock_level, is_featured, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, slug, description, price, category, image_url, stock_level, is_featured, metadata, created_at, updated_at
`

type CreateProductParams struct {
	Name        string                `json:"name"`
	Slug        string                `json:"slug"`
	Description sql.NullString        `json:"description"`
	Price       string                `json:"price"`
	Category    string                `json:"category"`
	ImageUrl    sql.NullString        `json:"image_url"`
	StockLevel  sql.NullInt32         `json:"stock_level"`
	IsFeatured  sql.NullBool          `json:"is_featured"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.queryRow(ctx, q.createProductStmt, createProduct,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Price,
		arg.Category,
		arg.ImageUrl,
		arg.StockLevel,
		arg.IsFeatured,
		arg.Metadata,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.ImageUrl,
		&i.StockLevel,
		&i.IsFeatured,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, username, email, password_hash, last_login FROM admins WHERE email = $1 LIMIT 1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.queryRow(ctx, q.getAdminByEmailStmt, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.LastLogin,
	)
	return i, err
}

const getAllProjects = `-- name: GetAllProjects :many
SELECT id, title, client, location, category, summary, thumbnail_url, gallery_urls, completion_year, is_highlight, created_at FROM projects ORDER BY created_at DESC
`

func (q *Queries) GetAllProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.query(ctx, q.getAllProjectsStmt, getAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Client,
			&i.Location,
			&i.Category,
			&i.Summary,
			&i.ThumbnailUrl,
			pq.Array(&i.GalleryUrls),
			&i.CompletionYear,
			&i.IsHighlight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHighlightedProjects = `-- name: GetHighlightedProjects :many
SELECT id, title, client, location, category, summary, thumbnail_url, gallery_urls, completion_year, is_highlight, created_at FROM projects WHERE is_highlight = TRUE ORDER BY completion_year DESC
`

func (q *Queries) GetHighlightedProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.query(ctx, q.getHighlightedProjectsStmt, getHighlightedProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Client,
			&i.Location,
			&i.Category,
			&i.Summary,
			&i.ThumbnailUrl,
			pq.Array(&i.GalleryUrls),
			&i.CompletionYear,
			&i.IsHighlight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestNews = `-- name: GetLatestNews :many
SELECT id, title, content, image_url, published_at FROM news ORDER BY published_at DESC LIMIT 5
`

func (q *Queries) GetLatestNews(ctx context.Context) ([]News, error) {
	rows, err := q.query(ctx, q.getLatestNewsStmt, getLatestNews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []News
	for rows.Next() {
		var i News
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ImageUrl,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, name, slug, description, price, category, image_url, stock_level, is_featured, metadata, created_at, updated_at FROM products WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.queryRow(ctx, q.getProductBySlugStmt, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Category,
		&i.ImageUrl,
		&i.StockLevel,
		&i.IsFeatured,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProducts = `-- name: GetProducts :many
SELECT id, name, slug, description, price, category, image_url, stock_level, is_featured, metadata, created_at, updated_at FROM products ORDER BY created_at DESC
`

func (q *Queries) GetProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.query(ctx, q.getProductsStmt, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.Category,
			&i.ImageUrl,
			&i.StockLevel,
			&i.IsFeatured,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
