// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	CreateInquiry(ctx context.Context, arg CreateInquiryParams) (Inquiry, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	GetAdminByEmail(ctx context.Context, email string) (Admin, error)
	GetAllProjects(ctx context.Context) ([]Project, error)
	GetHighlightedProjects(ctx context.Context) ([]Project, error)
	GetLatestNews(ctx context.Context) ([]News, error)
	GetProductBySlug(ctx context.Context, slug string) (Product, error)
	GetProducts(ctx context.Context) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
